# Generated by Django 3.2.5 on 2021-07-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('liked_user_id', models.IntegerField()),
            ],
        ),
    ]
