# Generated by Django 3.2.5 on 2021-07-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0005_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='C:\\Users\\pcadm\\djangostudy\\boardproject\\media\\ano.png', upload_to=''),
            preserve_default=False,
        ),
    ]
