# Generated by Django 3.2.5 on 2021-07-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0008_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
