# Generated by Django 3.2.5 on 2021-07-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0012_auto_20210712_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=50)),
                ('user_id', models.IntegerField()),
                ('talk_user_id', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
