# Generated by Django 3.2.5 on 2021-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0013_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
