# Generated by Django 3.2.5 on 2021-07-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0014_rename_liked_user_id_nopes_nope_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nopes',
            old_name='nope_user_id',
            new_name='noped_user_id',
        ),
    ]
