# Generated by Django 3.2.5 on 2021-07-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0015_auto_20210713_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='image',
        ),
    ]
