# Generated by Django 3.2.5 on 2021-07-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0015_rename_nope_user_id_nopes_noped_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nopes',
        ),
    ]
