# Generated by Django 3.2.5 on 2021-07-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0016_delete_nopes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('noped_user_id', models.IntegerField()),
            ],
        ),
    ]
