# Generated by Django 3.2.5 on 2021-07-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0017_messages_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='send_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
