# Generated by Django 3.2.5 on 2021-07-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0020_likes_send_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='send_date',
            new_name='like_date',
        ),
    ]
